### PR TITLE
Validate cert when there is only one

### PR DESCRIPTION
**Pull request by kacepe**
samlify stopped validate a cert because of this condition - I am sure that is a mistake.

### CODE REVIEW

**Comment by kacepe** [comment]
@tngan So idp must has at least 2 certificates to validate them?

**Comment by tngan** [comment]
@kacepe This is an additional feature in this library for checking if the certificate used in signing/encrypting document matches one of the certificates defined in metadata. We keep it for rolling certificate right now (i.e more than one certificate) but relax it for only one certificate.

If this is invalid certificate, the signature verification won't get passed. This check is just kind of pre-check before verification is carried out.

**Comment by legendary-mich** [comment]
@tngan Do you think that an evil guy would hand an invalid certificate over?

In our case, we have one cert in metadata, and one in the response. In that case samlify takes the one from the response and doesn't check it against the whitelist. So an evil guy can forge the response, sign it with whatever private key they want, and send it along with a cert that won't get validated, but will be used to verify the signature.

We had written integration tests for this scenario, and they rose an alarm once we updated the lib to 2.42. That's why we are here.

**Comment by tngan** [comment]
@legendary-mich This is definitely a valid concern and a security flaw. Since it's not guaranteed to have certificate embedded inside a response, would that be solved if I use the certificate defined in metadata instead of trusting the one from the response.

**Comment by legendary-mich** [comment]
@tngan Yes, the certificate from metadata works for me.

But even then it would do no harm to validate it against the whitelist. If you get the cert from metadata, and then you check if it is there, it will be there, because this is where you take it from. This way you add no exceptions, and just always validate, regardless if it comes from the response or from the metadata. Would you agree?

**Comment by tngan** [comment]
@legendary-mich After I have double checked the code base, I will approve this PR as it satisfies the following, thanks for your commit and clarification.

1) If response contains certificate, go through whitelist checking
2) If response doesn't contain certificate, skip whitelist checking (always true from whitelist checking as it uses the certificate in metadata by default)

**Comment by legendary-mich** [comment]
Sounds good.

**Pull request merged**
