### PR TITLE
[WIP] Elaborate internal types

### PR DESCRIPTION
**Pull request by Seikho**

### CODE REVIEW

**Comment by tngan** [comment]
@Seikho Once you think it's finished, we will have a final review and accept it, make sure you also remove the `WIP` if you think it's ready.

**Comment by Seikho** [comment]
There's still a bit to do here. I'm unsure if I've captured of all the "allowed" properties on the entity and metadata constructors.

**Comment by tngan** [comment]
No worries, I will review it before weekend.

**Comment by tngan** [comment]
@Seikho It's easy to modify later on, I can merge it first before I start working on the example using typescript as well, since we are now putting this definition in our own repo as you suggested before.

**Comment by tngan** [comment]
@Seikho I will merge this during this weekend first.

**Comment by Seikho** [comment]
No problem. I haven't had any time to come back and deep dive into this. I'm spread fairly thin at the moment with a few other projects.

**Pull request merged**
