### PR TITLE
Allow validating SAML responses without network connection

### PR DESCRIPTION
**Pull request by blackentropy**
By storing local copies of the dtd files and changing references
to refer to them, the samlify library no longer makes network requests
while validating XML.

Fixes https://github.com/nikku/node-xsd-schema-validator/issues/17

Addresses https://stackoverflow.com/questions/52392690/xsd-schema-validator-fails-to-validate-samlify-xml

### CODE REVIEW

**Comment by blackentropy** [comment]
You can verify this by using wireshark to log http requests while running the test suite.

**Comment by tngan** [comment]
For someone may worry about the source of the two .dtd files, I have double checked those two files are identical to 

1. https://www.w3.org/2001/XMLSchema.dtd and
2. https://www.w3.org/2001/datatypes.dtd

Credits to @blackentropy, thank you so much to remove that external request for these two .dtd files.

**Comment by hassanNS** [comment]
Thanks for this fix!

**Comment by sl45sms** [comment]
+1 
w3.org is down right now! 
this fix saves my hair.

**Comment by haoleman** [comment]
when is 2.4.2 getting released?

**Comment by tngan** [comment]
@haoleman Thanks for remind. v2.4.2 is just released.

**Pull request merged**
