### PR TITLE
updated xmlcrypto to 1.1.4

### LINKED ISSUE #244: Update to xmlcrypto 1.1.14?
We encountered this issue https://github.com/yaronn/xml-crypto/pull/172.  It has been fixed in xmlcrypto.  Is it possible to update to version 1.1.14?

### PR DESCRIPTION
**Pull request by lpamlie**
Fixes #244

### CODE REVIEW

**Comment by lpamlie** [comment]
Hi.  I'm a bit lost here.  I have a windows computer so I can't run the build locally and I really need this fix since the IdP we're integrating with has this namespace problem.  I would really appreciate it if you could help or give me some pointers on how to do this.  Thanks.

**Comment by tngan** [comment]
@lpamlie Which namespace problem are you referring to ?

**Comment by lpamlie** [comment]
Hi.

I’m referring to this issue:
https://github.com/yaronn/xml-crypto/issues/72

Here is the xml crypto pull request
https://github.com/yaronn/xml-crypto/pull/172

We encountered this problem with an IBM IdP.

Thanks
LP

**Comment by tngan** [comment]
Interesting, it breaks the tests.

**Comment by lpamlie** [comment]
Yes, I noticed that.  I also noticed that you had a fairly old version of xmlcrypto.

LP

**Comment by tngan** [comment]
It is. See if we can get rid of it soon then we are good to merge.

**Pull request merged**
