### PR TITLE
Add space replace to _normalizeCerString

### PR DESCRIPTION
**Pull request by ahwitz**
Hey - just switched over from passport-saml, and everything seems to be working fine, with one exception. `_normalizeCerString` on line 63 of /src/utility.ts strips all newlines/header/footer information from incoming certificates, but does not strip spaces. 

It seems like the Shibboleth IdP outputs its SAML `ds:X509Certificate` contents with spaces delimiting lines of the certificate. This has happened with both IdP instances I've been testing with, and is also present on https://www.testshib.org/metadata/testshib-providers.xml.

I somehow doubt this is syntactically correct, but would it be possible to add the attached `.replace(/ /g)` call to `_normalizeCerString`? I'm still new with SAML, so I'm not sure if this risks messing anything else up, but it's been working for me during testing.

Thanks! Let me know if anything else is needed from me.

### CODE REVIEW

**Comment by tngan** [comment]
@ahwitz Yep, thanks for your contribution, those spaces should be trimmed, please also fix the test cases then I will merge this pull request.

**Comment by ahwitz** [comment]
Let's see if moving the goalposts works... yarn and TypeScript are very foreign to me.

Also, as an FYI, either `tsc` or `tslint` failed with `node v6.9.1 (npm v3.10.8)`, but switching to Travis' `node v4.8.4 (npm 2.15.11)` worked.

**Comment by tngan** [comment]
@ahwitz This will be patched in v2.2.1 in the coming week.

**Comment by ahwitz** [comment]
Perfect. Thanks!

**Pull request merged**
